### ISSUE TITLE
changed personal name; hide former names

### ISSUE THREAD

**Issue by mariannevanharten** [FamilySearch/GEDCOM#545] opened 2024-08-30 12:36 UTC
I my tree I have persons who changed their name (several reasons).
I want to set a restriction to the former names, but
1 NAME John /Doe/
1 NAME Peter /Doe/
2 RESN CONFIDENTIAL
2 TYPE BIRTH
is not valid in Gedcom 7.0.14

Best regards,
Marianne van Harten

**Comment by fisharebest** [comment] 2024-08-30 12:57
This was proposed in issue #245.
The proposal was accepted for the next minor release - i.e. 7.1

**Comment by dthaler** [comment] 2024-09-03 16:27
Discussed in GEDCOM Steering Committee 3 SEP 2024:
Agreed this is a duplicate of issue #245, so closing this issue.
Please continue any discussion in that issue.
Thanks!

**Closed by dthaler** 2024-09-03 16:27 UTC
